server:
  port: 8760
spring:
  cloud:
    config:
      server:
        native:
          search-locations: file:///C:/WorkFolders/Spring Cloud/config
          version: 00.01
  profiles:
    active: native